# Generated by Django 2.0.2 on 2018-02-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('prob_type', models.CharField(choices=[('E', 'Erro'), ('Q', 'Dúvida'), ('S', 'Sugestão'), ('P', 'Pendência')], default=' ', max_length=1, verbose_name='Tipo')),
                ('priority', models.IntegerField(choices=[(0, 'Alta'), (1, 'Média'), (2, 'Baixa')], default=1, verbose_name='Prioridade')),
                ('versao', models.CharField(blank=True, max_length=20, verbose_name='Versão')),
                ('complete', models.BooleanField(default=False, verbose_name='Concluído?')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Pacote', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='pacote',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Project'),
        ),
    ]
