# Generated by Django 2.0.2 on 2018-02-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacote',
            unique_together={('projeto', 'name')},
        ),
    ]
